PREFIX gvri: <https://inf203.isped.fr/gvri#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
 
CONSTRUCT {
	?URI a gvri:Cim10;
	rdfs:label ?LAB;
  }
FROM <file:../../corpus/cim10.txt>
WHERE {
	BIND (URI(CONCAT("https://inf203.isped.fr/gvri/instances#cim10_", REPLACE(?CODE," ",""))) AS ?URI)
	BIND (STRLANG(?LIB,"fr") AS ?LAB)
  }