PREFIX gvri: <https://inf203.isped.fr/gvri#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
 
CONSTRUCT {
	?URI a gvri:MorphoCimo3;
	gvri:MorphoGrpIacr ?morpho;
	rdfs:label ?strfr;
  }
FROM <file:../../corpus/CIMO3_MORPHO.txt>
WHERE {
	BIND (URI(CONCAT("https://inf203.isped.fr/gvri/instances#morphoCimo_", REPLACE(?CODMORPHOCIMO3," ",""))) AS ?URI)
	BIND (URI(CONCAT("https://inf203.isped.fr/gvri/instances#morphoGrpIacr_",REPLACE(?GROUPE_MORPHO_IACR," ",""))) AS ?morpho)
	BIND (STRLANG(?LIBMORPHOCIMO3,"fr") AS ?strfr)
  }